### PR TITLE
(fix): remove faulty tsconfig.json include of test dir

### LINKED ISSUE #638: test/ dir is in `include`, non-spec TS files (e.g. test utils) break build with v0.13 rootDir: `./src`
### Current Behavior

Prior to v0.13 #504 , I could put a file into my test folder that contained utility code for tests and it would get compiled without a problem.

`test/TestUtils.tsx`

Now, when I `tsdx build`, I see this error:

`rpt2: options error TS6059: File '/mui-rff/test/TestUtils.tsx' is not under 'rootDir' '/mui-rff/src'. 'rootDir' is expected to contain all source files.`

### Expected behavior

I have a place to put utility code for tests.

### Suggested solution(s)

No idea, but you have a list of 3rd parties using this project and it would be nice if you would start to test future versions of tsdx against these projects to see if you break peoples stuff and can then use that to find out how to tell people how to fix their broken stuff.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | v0.13 |
| TypeScript       | 3.8.3 |
| npm/Yarn         |  6.13.7 / 1.22.4 | 
| Node             |  v13.11.0 |
| Operating System | OSX Catalina |

### PR DESCRIPTION
**Pull request by agilgur5**
- `include` means all files that should be compiled, and the test dir
  should definitely not be compiled
  - this was causing issues where declarations were being output into
    dist/ for all files in test/
    - that shouldn't happen and it means `build` was unnecessarily
      slowed down in order to process test/ files
    - default `exclude` that was added of *.spec/*.test files,
      originally for co-located tests, ended up making most test/ dir
      files excluded too, but not, say, test utils that don't have a
      .spec or .test suffix

- this was also causing errors with the `rootDir: './src'` change as
  the test/ dir is outside of the rootDir
  - problem wasn't the rootDir, but that the test/ dir shouldn't be
    compiled or processed in any way

(test): ensure test/*.test.ts and test/*.ts files are correctly
excluded and don't have declarations generated
- and that they don't error with rootDir: './src'

(test): ensure types/*.d.ts don't error with rootDir and don't have
declarations re-generated either
- n.b. tsc won't re-generate them either, they don't get copied to
  outDir, this isn't new or different behavior

(env/test): Jest shouldn't run / should ignore tests inside of fixtures

<hr>

Fixes #638 , the root cause of it, and adds tests for this.

Effectively reverts #226 . I haven't been able to reproduce #225 / #84 in my VS Code, but maybe that's because I have it configured a little differently?
Would like to add VS Code integration tests so there's an automated way to check that it works independently on CI without any configuration (and so I don't have to attempt and fail to test this on my own machine).
But `tsc --noEmit` at least, indeed doesn't output errors in `test/` anymore. `tsdx lint` still does.
Per my comments in #638 if this and the VS Code integration are problematic, we should move this to a `tsconfig.build.json` and then have a plain `tsconfig.json` that extends from it and changes `include` to `'./'` so everything is type-checked.

### CODE REVIEW

File: test/e2e/tsdx-build-default.test.js [hunk 1]
```diff
@@ -31,6 +31,15 @@ describe('tsdx build :: zero-config defaults', () => {
     expect(output.code).toBe(0);
   });
 
+  it("shouldn't compile files in test/ or types/", () => {
+    const output = execWithCache('node ../dist/index.js build');
+
+    expect(shell.test('-f', 'dist/test/')).toBeFalsy();
+    expect(shell.test('-f', 'dist/types/')).toBeFalsy();
```
Comment (agilgur5) [inline test/e2e/tsdx-build-default.test.js]: This should be [`-d` or `-e`](https://github.com/shelljs/shelljs#testexpression), not `-f`, which specifically checks for a file. I could test for the specific files too, but would prefer to keep it generic, as the directories shouldn't exist at all.

Comment (agilgur5) [reply test/e2e/tsdx-build-default.test.js]: used `-d` and tested to make sure it does give a test error when `test/` is erroneously in `include`.

**Comment by kylemh** [comment]
Does this mean we'd also wanna avoid compiling stories?

**Comment by agilgur5** [comment]
@kylemh yes, your stories shouldn't be in your `include`, otherwise they'll be unnecessarily compiled (and output to `dist`/likely unnecessarily published).

The Storybook template doesn't have them in the `include` as you can see here. Are yours by chance co-located? We could add `**/*.stories.tsx` to the default `exclude` if it's a common enough pattern (I've seen it a few times).

The approach I listed in https://github.com/jaredpalmer/tsdx/issues/638#issuecomment-605728767, especially with `file: ['src/index.ts']` is optimal, but unfortunately seems to have issues in upstream rpts2 as a I mentioned there.

**Comment by kylemh** [comment]
So I’m doing monorepo shit in a personal project first before I try to come up with a template to resolve #122

https://github.com/innocuous-tech/core

I’ve got it all flying for now, but I can’t see how to prevent the stories’ typings from getting compiled into the bundle.

I have it excluded... what do you think?

**Comment by agilgur5** [comment]
Ah yours are like semi-colocated, in the `src` dir but as separate dirs. I'd leave them outside of `src` for a template fwiw.
Probably just need to mess with the globs a bit. If you moved the `exclude` into each package it would probably be easier to figure out. Path resolution is a bit weird with `extends` too but you seem to be using it correctly so I'm not sure.

**Comment by kylemh** [comment]
Hmmmm I remember reading somewhere that @jaredpalmer prefers colocating tests with source code. Having the answer be “don’t do that” doesn’t seem ideal.

I’ll try manually listing the excludes in each package, but that wasn’t working either.

**Comment by agilgur5** [comment]
Well none of the existing templates have co-located tests or stories, so it wouldn't make sense to add a monorepo template that is the odd one out has semi-colocated tests. Would be very inconsistent and confusing to users

**Comment by kylemh** [comment]
So this is my individual use case. I can make the template match the rest. The point I’m making is that we should be able to have collocated tests and stories.

In my example, test files are ignored but not stories, so I was just tryna make sure it wasn’t something under the hood. Not extending and excluding per package seems to be working. I’ll have to figure out where I’m going wrong with `extends`

**Comment by agilgur5** [comment]
The `include`/`exclude` handling should work the same as `tsc`, the only difference is that TSDX a default `exclude` for fully co-located tests (if you're adding your own it doesn't matter). Though it's possible there are bugs with rpts2 as that's one reason why I haven't moved templates to just a `files` set-up which wouldn't be impacted by location at all, only by imports.
